### ISSUE TITLE
facebook 공유 이미지가 잘못됨 ( 포스팅, disqus)

### ISSUE THREAD

**Issue by dalzony** [clojure-korea/clojure.kr#7]

**Comment by eunmin** [comment]
링크는 잘 된 것 같은데 이미지가 이상하게 나와요. 주소를 복붙해서 페북에 포스팅해보려고 했는데 똑같네요. 페이지에서 메타 정보를 잘 못 쓰고 있는 것 같네요.

**Comment by dalzony** [comment]
@eunmin 넵 이슈명 고쳤습니다 ㅋ, 개인 블로그에선 별다른 설정없이 했는데, 이상하네욥

**Comment by dalzony** [comment]
수정, 적용된 것 확인 완료
